# Generated by Django 4.1.1 on 2022-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, upload_to='games/videos/'),
        ),
    ]
